Name:           ros-lunar-katana-teleop
Version:        1.1.1
Release:        0%{?dist}
Summary:        ROS katana_teleop package

Group:          Development/Libraries
License:        GPL
URL:            http://ros.org/wiki/katana_teleop
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-lunar-actionlib
Requires:       ros-lunar-control-msgs
Requires:       ros-lunar-katana-msgs
Requires:       ros-lunar-roscpp
Requires:       ros-lunar-sensor-msgs
BuildRequires:  ros-lunar-actionlib
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-control-msgs
BuildRequires:  ros-lunar-katana-msgs
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-sensor-msgs

%description
This package provides tele-operation nodes to control the Neuronics Katana 450
arm via keyboard commands or with a playstation 3 controller.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Fri May 26 2017 Henning Deeken <hdeeken@uni-osnabrueck.de> - 1.1.1-0
- Autogenerated by Bloom

* Fri May 26 2017 Henning Deeken <hdeeken@uni-osnabrueck.de> - 1.1.0-0
- Autogenerated by Bloom

* Wed May 24 2017 Henning Deeken <hdeeken@uni-osnabrueck.de> - 1.0.7-0
- Autogenerated by Bloom

